astropython/astropython/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib import admin

from moderation.helpers import auto_discover

from main.views import *

admin.autodiscover()
auto_discover()# from moderation app -alway keep below admin.autodiscover()

urlpatterns = patterns('',
    url(r'^grappelli/', include('grappelli.urls')), #for admin urls
    url('', include('social.apps.django_app.urls', namespace='social')), #for social auth urls
    url(r'^admin/', include(admin.site.urls)), #additional admin urls
    url(r'^search$','main.views.search',name="search"),
    url(r'^$', 'main.views.home', name='home'),#home url
    url(r'^logout/', 'main.views.logout_view', name='logout'),#Sample Templates
    url(r'',include('main.urls')),#Teach and Learn
)

#Access Static Files if in development
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

astropython/main/urls.py
from django.conf.urls import patterns,url,include

from .models import *
from .views import *
from .feeds import *

urlpatterns = patterns('',
    url(r'^(?P<section>announcements|blog|education|events|news|packages|snippets|tutorials|wiki)/create$',create,name="create"),
    url(r'^(?P<section>announcements|blog|education|events|news|packages|snippets|tutorials|wiki)/create/(?P<slug>[\w-]+)$',create,name="create"),
    url(r'^(?P<section>announcements|blog|education|events|news|packages|snippets|tutorials|wiki)/(?P<slug>[\w-]+)/$',single,name="single"),
    url(r'^(?P<section>announcements|blog|education|events|news|packages|snippets|tutorials|wiki)/(?P<slug>[\w-]+)/(?P<choice>upvote|downvote)/$',vote,name="vote"),
    url(r'^(?P<section>announcements|blog|education|events|news|packages|snippets|tutorials|wiki)/$',all,name="all"),
    url(r'^user/posts$',written,name="user_posts"),
    url(r'^contact$',contact,name="contact"),
    url(r'^timeline/(?P<section>tl|forum|all)$',timeline,name="timeline"),
    url(r'^feeds/rss$',RSSFeed(),name="rss_feed"),
    url(r'^feeds/atom$',ATOMFeed(),name="atom_feed"),
    url(r'^feeds/update$',update_feed,name="update_feed"),
    url(r'^feeds/list$',display_feed_list,name="list_feed"),
    )

astropython/main/models.py
"""
Define structures of models.
Each model is automatically translated to database schemas.
"""
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from taggit.managers import TaggableManager

import secretballot
import watson

from django.db.models.signals import post_save
from .signals import add_to_preview,add_content
from astropython.settings import STATE_CHOICES,INPUT_CHOICES

PACKAGE_CHOICES = (
	('Recommended', 'Recommended'),
	('Others', 'Others'),
 )

SECTION_CHOICES = (
	('tutorials', 'Tutorials'),
	('snippets', 'Code Snippets'),
    ('education', 'Educational Resources'),
	('wiki', 'Wiki Pages'),
    ('announcements', 'Announcements'),
	('news', 'News'),
    ('blog', 'Blog'),
	('packages', 'Packages'),
    ('events', 'Events'),
 )

class BasePost(models.Model):
    title = models.CharField(max_length=200)#Title of the Post
    input_type=models.CharField(max_length=60,choices=INPUT_CHOICES,default="Markdown",verbose_name='Text Editor Choice',help_text='All current editor contents will be lost once editors are switched')
    abstract = models.TextField(blank=True,default="",help_text='Optional Summary of Post') #Short abstract of the tutorial
    authors = models.ManyToManyField(User,blank=True,null=True) # Collaborators of a tutorial
    body = models.TextField(blank=False,verbose_name='Page Body / Contents')
    slug = models.SlugField(unique=True) #Slug to a tutorial
    state = models.CharField(max_length=60,choices=STATE_CHOICES,default='raw') #State of a tutorial
    tags=TaggableManager() #Tags
    created = models.DateTimeField(auto_now_add=True, auto_now=False)  # Date when first revision was created
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)  # Date when last revision was created (even if not published)

    def __unicode__(self):
		return self.title

    class Meta:
        abstract=True

class Tutorial(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'tutorials','slug':self.slug})

class Snippet(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'snippets','slug':self.slug})

class Wiki(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'wiki','slug':self.slug})

class Announcement(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'announcements','slug':self.slug})

class News(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'news','slug':self.slug})

class Blog(BasePost):

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'blog','slug':self.slug})

class Package(BasePost):
    category=models.CharField(max_length=60,choices=PACKAGE_CHOICES,default="Others",help_text='Packages not actively mantained are labelled "Others"')
    homepage=models.URLField(blank=True,verbose_name="Homepage URL")#URL : homepage of the packages
    docs = models.URLField(blank=True,verbose_name="URL to Docs")

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'packages','slug':self.slug})

class EducationalResource(BasePost):
    start_date = models.DateTimeField(null=True, blank=True,help_text="Format : YYYY-MM-DD")#Date the course starts
    instructor_names = models.CharField(max_length=400)#Names of Instructors
    website = models.URLField(blank=True,verbose_name='Course Website')#Website hosting the course, or having more info about the course
    contents = models.TextField(blank=True,verbose_name='Course Contents') #Syllabus or contents of the course
    background = models.TextField(blank=True,verbose_name='Recommended Background')#Recommended Backgroud
    faq=models.TextField(blank=True,verbose_name='Frequently Asked Questions')#FAQ if any
    language = models.CharField(max_length=200,blank=True,verbose_name='Language of Instruction')#Language in which course is to be conducted

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'education','slug':self.slug})

"""
Events model are associated with any future events that are planned
"""
class Event(models.Model):
    title = models.CharField(max_length=200)
    input_type=models.CharField(max_length=60,choices=INPUT_CHOICES,default="Markdown",verbose_name='Text Editor Choice',help_text='All current editor contents will be lost once editors are switched')
    authors = models.ManyToManyField(User,blank=True,null=True) # Collaborators of a tutorial
    body =models.TextField(blank=False,verbose_name='Page Body / Contents')
    location = models.CharField(max_length=1000,blank=True)
    website = models.URLField(blank=True)
    slug = models.SlugField(unique=True)
    state = models.CharField(max_length=60,choices=STATE_CHOICES,default='raw')
    tags=TaggableManager()
    created = models.DateTimeField(auto_now_add=True, auto_now=False)  # Date when first revision was created
    updated = models.DateTimeField(auto_now_add=False, auto_now=True)  # Date when last revision was created (even if not published)
    start_date_time = models.DateTimeField(help_text="Format : YYYY-MM-DD")#start time
    end_date_time = models.DateTimeField(blank=True, null=True,help_text="Format : YYYY-MM-DD")#When dies the event end
    all_day_event = models.BooleanField(default=False)#If it is an all day event

    def __unicode__(self): #Format of representation of event
        date_format = '%Y-%m-%d %I:%M %p'
        if self.all_day_event:
            date_format = '%Y-%m-%d'
        return '%(n)s (%(d)s)' % {'n': self.title, 'd': self.start_date_time.strftime(date_format), }

    def active(self):#IF event is active
        if self.start_date_time and self.end_date_time:
            t = timezone.now()
            return self.start_date_time <= t and self.end_date_time >= t
        return False
    active.boolean = True

    def get_absolute_url(self):
        return reverse('main.views.single',kwargs={'section':'events','slug':self.slug})

class Contact(models.Model):
    username=models.CharField(max_length=60)
    email=models.CharField(blank=False,max_length=60)
    content=models.TextField(blank=False)

    def __unicode__(self):
		return self.content

class Feed(models.Model):
    title=models.CharField(max_length=120,blank=False)
    url=models.URLField(blank=False)
    section=models.CharField(max_length=60,choices=SECTION_CHOICES,default="blog")
    notes=models.TextField(blank=True)

    def __unicode__(self):
		return self.title

post_save.connect(add_to_preview,sender=User)
post_save.connect(add_content,sender=Tutorial)
post_save.connect(add_content,sender=Snippet)
post_save.connect(add_content,sender=Wiki)
post_save.connect(add_content,sender=Announcement)
post_save.connect(add_content,sender=News)
post_save.connect(add_content,sender=Blog)
post_save.connect(add_content,sender=Event)
post_save.connect(add_content,sender=EducationalResource)
post_save.connect(add_content,sender=Package)


secretballot.enable_voting_on(Tutorial)
secretballot.enable_voting_on(Snippet)
secretballot.enable_voting_on(Wiki)
secretballot.enable_voting_on(Announcement)
secretballot.enable_voting_on(News)
secretballot.enable_voting_on(Blog)
secretballot.enable_voting_on(Event)
secretballot.enable_voting_on(EducationalResource)
secretballot.enable_voting_on(Package)

watson.register(Tutorial)
watson.register(Snippet)
watson.register(Wiki)
watson.register(Announcement)
watson.register(News)
watson.register(Blog)
watson.register(EducationalResource)
watson.register(Package)
watson.register(Event)

astropython/templates/complete.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block head_title %}
{{name}}:
{% endblock %}
{% block styles %}
{% endblock %}
{% block content %}
<div class="container mtb">
<div class="row">
	<! --LIST-->
	<div class="col-lg-12">
		<div style="text-align:center;color:orange">
			<img src='{% static "images/complete_icon.png" %}' height="100px" width="100px"> 
			{% if state == "raw" %}
			<h2>Your post has been saved !</h2>
			<p> Come back later and complete it <a href="/{{section}}/create/{{slug}}">here</a> or access it from the 'My Posts' section of the navigation bar above !</p>
			{% elif state == "feed_update" %}
			<p>All the feeds have been updated ! <br/> The new posts are awaiting Moderator approval....</p>
			{% else %}
			<h2>Your post has been submitted !</h2>
			<p> Access it <a href="/{{section}}/{{slug}}">here</a> <br/> Moderation has been temporarily revoked for our preview users !</p>
			{% endif %}
			<p><a href="/">Return to Home</a></p>
			<p><a href="/{{section}}">Return to Section Homepage</a></p>
		</div>
	</div><! --/col-lg-8 -->
</div><! --/row -->
</div><! --/container -->


{% endblock %}

astropython/templates/creation.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load compress %}
{% block head_title %}
{{name}} Creation: 
{% endblock %}
{% block styles %}
{{form.media}}
 <link rel="stylesheet" href="{{STATIC_URL}}markdown/css/editormd.css" />
{% endblock %}
{% load crispy_forms_tags %}

{% block js %}
{% compress js %}
<script src="{{STATIC_URL}}markdown/editormd.js"></script>
<script src="{{STATIC_URL}}markdown/languages/en.js"></script>
<script src="{{STATIC_URL}}ckeditor/ckeditor.js"></script> 
<script type="text/javascript">
	$(document).ready(function(){
			var testEditormd;
			$("#id_input_type").change(function(){
				$("#conform_modal").modal("show");
				});
			$('.tag-cloud a').click(function(e) {
				  var txt = $(e.target).text();
				  var curr_tags = $('#id_tags').val();
				  if(curr_tags==''){
				  $('#id_tags').val(txt);
				  }else{
				  $('#id_tags').val(curr_tags+','+txt);
				  }
				});
			$("#id_abstract").attr({"rows": "4"});
			changeEditor();
	});
	function revert(in_type){
		if(in_type=="WYSIWYG"){
		$('#id_input_type option[value="Markdown"]').attr("selected","selected");
		}
		else{
		$('#id_input_type option[value="WYSIWYG"]').attr("selected","selected");
		}
		$("#conform_modal").modal("hide");
	}
	function changeEditor(){
			ch=$("#id_input_type option:selected").val();
				if (ch=="WYSIWYG")
				{
					try{
					testEditormd.editor.remove();
					$("#div_id_body > .controls").append('<textarea class="textarea form-control" cols="40" id="id_body" name="body" rows="10"></textarea>');
					}catch(err)
					{
					}
					 CKEDITOR.config.removePlugins='floating-tools';
					CKEDITOR.replace( 'body' );
				}
				else{
					for(name in CKEDITOR.instances)
					{
						CKEDITOR.instances[name].destroy()
					}
					$("#id_body").replaceWith('<div id=\"test-editormd\"><textarea style="display:none;">{% if form.body.value and form.input_type.value == "Markdown" %}{{form.body.value|escapejs}}{% endif %}</textarea></div>');
					testEditormd = editormd("test-editormd", {
						width: "100%",
						height : 800,
						path : '{{STATIC_URL}}markdown/lib/',
						tex:true,
						emoji:true,
						taskList:true,
						flowChart:true, 
						sequenceDiagram:true,
						codeFold : true,
                        syncScrolling : true,
                        searchReplace : true,
                        previewCodeHighlight : true,
                        tocm : true,
                        imageUpload : false,
					});
					$(".editormd-markdown-textarea").attr("name","body");
				}
			}
</script>

{% endcompress %}
{% endblock %}
{% block content %}
<!-- *****************************************************************************************************************
TITLE WRAP
***************************************************************************************************************** -->
<section id="page-breadcrumb">
	<div class="vertical-center sun">
		 <div class="container">
			<div class="row">
				<div class="action">
					<div class="col-sm-12">
						<h1 class="title" id="title">Create {{name}} !</h1>
					</div>                                                                                
				</div>
			</div>
		</div>
	</div>
</section>
<!-- *****************************************************************************************************************
BLOG CONTENT
***************************************************************************************************************** -->
<div class="modal fade" id="conform_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header" style="text-align:center;">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h2 class="modal-title" id="myModalLabel">Conformation</h2>
		<h5>Once you change editors, the current editor contents will be lost.</h5>
      </div>
      <div class="modal-body">
		<div class="btn-group" role="group" aria-label="..." style="left:25%;">
		  <button type="button" class="btn btn-success" onclick='changeEditor();$("#conform_modal").modal("hide");'>Yes, I am sure !</button>
		  <button type="button" class="btn btn-danger" onclick='revert($("#id_input_type option:selected").val());'>No, take me back !</button>
		</div>
      </div>
    </div>
  </div>
</div>
<section id="blog-details" class="padding-top">
<div class="container">
<div class="row">
	<div class="col-lg-12">
	<form method="POST">{% csrf_token %}
	{{form|crispy}}
	{% if tags %}
	<div class="tag-cloud" style="margin-bottom:30px;">
		<h3>Current Tags</h3>
		<h6>(Click on the tag names to add them)</h6>
		<ul class="nav nav-pills">
		{% for tag in tags %}
			<li><a>{{tag}}</a></li>
		{% endfor %}
		</ul>
	</div>
	{% endif %}
	<button type="submit" name="submit" class="btn btn-warning">Publish</button>
	{% if user.is_authenticated %}
	<button type="submit" name="save" class="btn btn-warning">Save</button>
	{% endif %}
	</form>
	</div><! --/col-lg-8 -->
</div>
</div>
</section>
{% endblock %}
{% block endjs %}
{% endblock %}

astropython/templates/edit_modal.html
<!-- Modal -->
{% load crispy_forms_tags %}
<div class="modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Post</h4>
      </div>
      <div class="modal-body">
			<form method="POST" action="">{% csrf_token %}
			{{form|crispy}}
			<button type="submit" name="submit" class="btn btn-warning">Confirm Edit</button>
			</form>
      </div>
      <div class="modal-footer">
	  <p> All Edits are subject to Moderation</p>
      </div>
    </div>
  </div>
 </div>
{% if obj.input_type == "WYSIWYG" %}
	<script type="text/javascript">CKEDITOR.replace( 'body' );</script>
{% endif %}

astropython/templates/single.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load compress %}
{% block head_title %}
{{obj.title}} :
{% endblock %}
{% load crispy_forms_tags %}
{% block styles %}
{{form.media}}
 <link rel="stylesheet" href="{{STATIC_URL}}markdown/css/editormd.css" />
<script type="text/javascript">var switchTo5x=true;</script>
<script type="text/javascript" src="http://w.sharethis.com/button/buttons.js"></script>
<script type="text/javascript">stLight.options({publisher: "626bc566-fe39-4650-9440-d70b61157997", doNotHash: false, doNotCopy: false, hashAddressBar: false});</script>
{% endblock %}
{% block js %}
{% if obj.input_type == "WYSIWYG" and mode == "edit" %}
<script src="{{STATIC_URL}}ckeditor/ckeditor.js"></script> 
{% endif %}
{% if obj.input_type == "Markdown" %}
<script src="{{STATIC_URL}}markdown/lib/marked.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/prettify.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/raphael.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/underscore.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/sequence-diagram.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/flowchart.min.js"></script>
<script src="{{STATIC_URL}}markdown/lib/jquery.flowchart.min.js"></script>
<script src="{{STATIC_URL}}markdown/editormd.js"></script>
<link rel="stylesheet" href="{{STATIC_URL}}markdown/css/editormd.preview.css" />
<script type="text/javascript">
	$(document).ready(function(){
			{% if mode == "edit" %}
			$("#id_body").replaceWith('<div id=\"test-editormd\"><textarea style="display:none;">{{obj.body|escapejs}}</textarea></div>');
			testEditormd = editormd("test-editormd", {
						width: "100%",
						height : 800,
						path : '{{STATIC_URL}}markdown/lib/',
						tex:true,
						emoji:true,
						taskList:true,
						flowChart:true, 
						sequenceDiagram:true,
						codeFold : true,
                        syncScrolling : true,
                        saveHTMLToTextarea : true,
                        searchReplace : true,
                        previewCodeHighlight : true,
                        tocm : true,
                        imageUpload : false,
					});
					$(".editormd-markdown-textarea").attr("name","body");
			$("#edit_modal").modal("show");
			{% endif %}
			
            $(function() {
                var testEditormdView;
				    testEditormdView = editormd.markdownToHTML("test-editormd-view", {
                        //htmlDecode      : true,  
                        htmlDecode      : "style,script,iframe", 
                        //toc             : false,
                        tocm            : true,    // Using [TOCM]
                        //tocContainer    : "#custom-toc-container"
                        gfm             : true,
                        tocDropdown     : true,
                        // markdownSourceCode : true, // 
                        emoji           : true,
                        taskList        : true,
                        tex             : true, 
                        flowChart       : true,  
                        sequenceDiagram : true,  
                   
                });
            });
	});
</script>
{% else %}
{% if mode == "edit" %}
<script>
$(document).ready(function(){
$("#edit_modal").modal("show");});
</script>
{% endif %}
{% endif %}
{% endblock %}
{% block content %}
<!-- *****************************************************************************************************************
TITLE WRAP
***************************************************************************************************************** -->
<section id="page-breadcrumb">
	<div class="vertical-center sun">
		 <div class="container">
			<div class="row">
				<div class="action">
					<div class="col-sm-12">
						<h1 class="title" id="title">{{obj.title}}</h1>
						{% if section == "wiki" %}
						<a href="../{{section}}/create"><img src='{% static "images/add_new.png" %}' height="50px" width="50px" style="position: absolute;right: 0px;bottom:0px;"> </a>
						{% endif %}
					</div>                                                                                
				</div>
			</div>
		</div>
	</div>
</section>
<!-- *****************************************************************************************************************
BLOG CONTENT
***************************************************************************************************************** -->
{% if mode == "edit" %}
{% include 'edit_modal.html' %}
{% endif %}
<section id="blog-details" class="padding-top">
<div class="container">
	<div class="row">
	<div class="col-md-9 col-sm-9" style="word-wrap: break-word;margin-left:0px;">
		<div class="row">
			 <div class="col-md-12 col-sm-12">
			  
			 {% if section == "wiki" %}
			 <div style="text-align:right">
			 <a href="?edit=body"><h5>Add to this Wiki Page</h5></a>
			 </div>
			 {% endif %}
				<div class="single-blog blog-details two-column">
					<div class="post-content overflow">
						{% if obj.abstract %}
							<p id="abstract"><b>Abstract :</b> {% autoescape off %}{{obj.abstract}}{% endautoescape %}</p>
						{% endif %}
						{% if section == "packages" %}
							<p id="category"><b>Category : </b>{{obj.category}}</p>
							{% if obj.homepage %}
							<p id="homepage"><b>Homepage : </b><a href="{{obj.homepage}}">{{obj.homepage}}</a></p>
							{% endif %}
							{% if obj.docs %}
							<p id="docs"><b>Documentation: </b><a href="{{obj.docs}}">{{obj.docs}}</a></p>
							{% endif %}
						{% endif %}
						{% if section == "events" %}
							{% if obj.website %}
							<p id="website"><b>Event Website : </b><a href="{{obj.website}}">{{obj.website}}</a></p>
							{% endif %}
							{% if obj.location %}
							<p id="location"><b>Location : </b>{{obj.location}}</p>
							{% endif %}
							<p id="start_date_time"><b>Event Date: </b>{{obj.start_date_time|date}}</p>
							{% if obj.end_date_time %}
							<p id="end_date_time"><b>Event End Date : </b>{{obj.end_date_time|date}}</p>
							{% endif %}
							{% if obj.all_day_event %}
							<p>This is an all day event !</p>
							{% endif %}
						{% endif %}
						{% if obj.input_type == "Markdown" %}
						<div id="test-editormd-view">
						<textarea style="display:none;" name="test-editormd-markdown-doc">{{obj.body}}</textarea>               
						</div>
						{% else %}
						<p id="body_display">{% autoescape off %}{{obj.body}}{% endautoescape %}</p>
						{% endif %}
						<br/>
						{% if section == "education" %}
							<p id="start_date"><b>Start Date : </b>{{obj.start_date}}</p>
							<p id="instructor_names"><b>Instructors : </b>{{obj.instructor_names}}</p>
							<p id="website"><b>Website : </b><a href="{{obj.website}}">{{obj.website}}</a></p>
							<p id="language"><b>Language : </b>{{obj.language}}</p>
							<p id="contents"><h4>Course Structure & Contents </h4><br/>{{obj.contents}}</p>
							<br/>
							<p id="background"><h4>Recommended Background </h4><br/>{{obj.background}}</p>
							<br/>
							<p id="faq"><h4>Frequently Asked Questions </h4><br/>{{obj.faq}}</p>
							<br/>
						{% endif %}
						{% if section != "wiki" %}
						 <div style="text-align:right">
						 <a href="?edit=body"><h5>Edit Main Contents</h5></a>
						 </div>
						 {% endif %}
						<br/>
						<h5 class="post-author">Posted by <a><b>{% for users in obj.authors.all %}{{users.username}}{% endfor %}</b></a></h5>
							<div class="sidebar-item tag-cloud">
								<h3 id="tags">Tags</h3>
								<ul class="nav nav-pills">
								{% for tag in obj.tags.all %}
									<li><a href="/{{section}}/?tags={{tag.name}}"><b>{{tag.name}}</b></a></li>
								{% endfor %}
								</ul>
							</div>
							<div style="text-align:center">  
								<a href="./upvote"><i class="glyphicon glyphicon-thumbs-up"></i>&nbsp&nbsp&nbsp <span class="badge">{{obj.total_upvotes}}</span></a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
								<a href="./downvote"><i class="glyphicon glyphicon-thumbs-down"></i>&nbsp&nbsp&nbsp <span class="badge">{{obj.total_downvotes}}</span></a>
								<div class="spacing"></div>
								<h6>SHARE</h6>
								<span class='st_facebook_large' displayText='Facebook'></span>
								<span class='st_twitter_large' displayText='Tweet'></span>
								<span class='st_googleplus_large' displayText='Google +'></span>
								<span class='st_email_large' displayText='Email'></span>
							</div>
						<div class="response-area">
						<h2 class="bold">Comments</h2>
						<div id="disqus_thread" style='margin-top:50px;'></div>
						</div><!--/Response-area-->
					</div>
				</div>
			</div>
		</div>
	 </div>
	<script type="text/javascript">
		$( "#title,#abstract,#tags,#category,#homepage,#docs,#start_date_time,#end_date_time,#website,#location,#start_date,#instructor_names,#website,#language,#contents,#background,#faq").hover(
		  function() {
			attribute=$(this).attr('id');
			$( this ).append( $( "<span>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href='?edit="+attribute+"'><img src='{% static 'images/edit_logo.png' %}' height='15px' width='15px'></a></span>" ) );
		  }, function() {
			$( this ).find( "span:last" ).remove();
		  }
		);
	</script>
	<script type="text/javascript">
		/* * * CONFIGURATION VARIABLES * * */
		var disqus_shortname = 'astropython'; //registered short name of astropython
		var disqus_identifier= '{{full_url}}';
		var disqus_url = '{{full_url}}';
		/* * * DON'T EDIT BELOW THIS LINE * * */
		(function() {
			var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
			dsq.src = 'http://' + disqus_shortname + '.disqus.com/embed.js';
			(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
		})();
		(function () {
			var s = document.createElement('script'); s.async = true;
			s.type = 'text/javascript';
			s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
			(document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
		}());
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
	
	<!--End of comments section-->

	{% include 'sidebar.html' %}	
	</div>
</div>
</section>
{% endblock %}
{% block endjs %}
{% endblock %}

astropython/templates/site_base.html
{% extends "base.html" %}